--db 저장해놓는 메모 용도로 , 파일로 관리해놓자.

drop table if exists member cascade;
create table member
(
 id bigint generated by default as identity, // 값 세팅 안하면 db가 id 채워줌
 name varchar(255),
 primary key (id)
);
